apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
  namespace: giropops
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-deployment
  strategy: 
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
        - image: nginx:1.15.0
          imagePullPolicy: Always
          name: nginx
          resources:
            requests:
              cpu: "0.3"
              memory: "64Mi"
            limits:
              cpu: "0.5"
              memory: "128Mi"

              
