apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: lento
  name: my-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt/data
  storageClassName: giropops-sc
