apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  serviceName: "nginx"
  replicas: 3
  selector: 
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      name: nginx
    spec:
      containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: nginx-persistent-storage
              mountPath: /usr/share/nginx/html
          resources:
            requests:
              cpu: "0.3"
              memory: "64Mi"
            limits:
              cpu: "0.5"
              memory: "128Mi"
  volumeClaimTemplates:
    - metadata:
        name: nginx-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi